config/routes.rb
Rails.application.routes.draw do

  resources :exit_surveys, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'exit_surveys#index', :as => 'search'
      post 'reports/output_reports.xls', to: 'exit_surveys#output_reports'
    end
   end
  devise_for :users
  root to: 'home#index'
  resources :employees, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'employees#index', :as => 'search'
    end
end

  resources :entrance_surveys, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'entrance_surveys#index', :as => 'search'
      post 'reports/entrance_surveys.xls', to: 'entrance_surveys#xls_report'
    end
  end

  resources :reports

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :gender
  has_many :exit_surveys
  has_many :entrance_surveys
  # belongs_to :company
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :destroy]

  $user = ""

  def index
    employee = params[:search].to_i
    @employees = Employee.all
    #.paginate(:page => params[:page], :per_page => 5)
    result = Employee.find_by_document_number(employee)

    if result.present?
      $user = result.document_number
      @employees = Employee.where(document_number: $user)
    elsif !result.present? && employee != 0
      @error = true
    end
  end

  def new
    @employee = Employee.new
  end


  def create
    @employee = Employee.new(employee_params)
    if Employee.where(:document_number => @employee.document_number).present?
      sweetalert_warning("el empleado con el numero de documento #{@employee.document_number} ya existe", 'Ya existe', persistent: 'Aceptar')
      redirect_to action: "create"
    else
      @employee.responsible = "ANDRES"
      @employee.responsible_position = "Resepcion"
      @employee.imc = calculate_data
      @employee.interpretation = calculate_portion
      @employee.date_and_time = Time.now.strftime("%d-%m-%Y %I:%M %p")
      respond_to do |format|
        if @employee.save
          sweetalert_success("El empleado #{@employee.name} se ha registrado con exito", 'Creado', persistent: 'Aceptar')
          redirect_to action: "create"
          format.json { head :no_content }
          format.js
        else
          format.json { render json: @employee.errors.full_messages, status: :unprocessable_entity }
          format.js { render :new }
        end
      end
    end
  end

  def calculate_data
    weight = @employee.weight.to_f
    height = @employee.size
    @imc = weight/(height * height)
    @imc.ceil(2)
  end

  def calculate_portion
    if((@imc < 18.5) || (@imc == 18.5))
      @imc_result = 'DESNUTRICION'
    elsif((@imc > 18.5) && (@imc < 25))
      @imc_result = 'NORMAL'
    elsif((@imc > 24.9) && (@imc < 30))
      @imc_result = 'SOBREPESO'
    elsif((@imc > 30) && (@imc == 30))
      @imc_result = 'OBESIDAD'
    end
  end

  # def calculate_muscle_mass_index
  #   #weight = peso
  #   weight = @employee.weight.to_f
  #   height = @employee.size
  #   @imc = weight/(height * height)
  #
  #   if((@imc < 18.5) || (@imc == 18.5))
  #     @imc_result = 'DESNUTRICION'
  #   elsif((@imc > 18.5) && (@imc < 25))
  #     @imc_result = 'NORMAL'
  #   elsif((@imc > 24.9) && (@imc < 30))
  #     @imc_result = 'SOBREPESO'
  #   elsif((@imc > 30) && (@imc == 30))
  #     @imc_result = 'OBESIDAD'
  #   end
  # end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        sweetalert_success("El empleado #{@employee.name} se ha editado con exito", 'Actualizado', persistent: 'Aceptar')
        redirect_to action: "index"
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @employee.errors.full_messages, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:responsible, :responsible_position, :document_number, :name, :organizational_unit, :position, :gender_id, :eps, :age, :blood_type, :phone, :emergency_number, :weight, :size, :imc, :interpretation, :date_and_time)
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee, remote: true do |f| %>
  <div class="form-group">
    <h4 class="control-label">Datos del empleado: </h4>
  </div>

  <div class="item form-group<%= @employee.errors[:document_number].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :document_number, "Documento de Identidad: " %>
    <div class="input-group">
      <%= f.number_field :document_number, {:class => "form-control", :placeholder => "Ingrese numero de documento", required:'true'} %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:name].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :name, "Nombre: " %>
    <div class="input-group">
      <%= f.text_field :name, {:class => "form-control", :placeholder => "Ingrese nombre", required:'true'} %>
      <%if @employee.errors[:name].any? %>
        <p class="bg-danger"><%= @employee.errors[:name].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:organizational_unit].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :organizational_unit, "Unidad Organizativa: " %>
    <div class="input-group">
      <%= f.text_field :organizational_unit, {:class => "form-control", :placeholder => "Ingrese la Unidad Organizativa", required:'true'} %>
      <%if @employee.errors[:organizational_unit].any? %>
        <p class="bg-danger"><%= @employee.errors[:organizational_unit].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:position].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :position, "Cargo: " %>
    <div class="input-group">
      <%= f.text_field :position, {:class => "form-control", :placeholder => "Ingrese cargo", required:'true'} %>
      <%if @employee.errors[:position].any? %>
        <p class="bg-danger"><%= @employee.errors[:position].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:gender_id].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :gender_id, "Genero: " %>
    <div class="input-group">
      <%= f.collection_select :gender_id, Gender.all, :id, :description, { :prompt => "Seleccionar" }, { :class => "form-control"  }%>
      <%if @employee.errors[:gender_id].any? %>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:eps].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :eps, "EPS: " %>
    <div class="input-group">
      <%= f.text_field :eps, {:class => "form-control", :placeholder => "Ingrese EPS", required:'true'} %>
      <%if @employee.errors[:eps].any? %>
        <p class="bg-danger"><%= @employee.errors[:eps].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:age].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :age, "Edad: " %>
    <div class="input-group">
      <%= f.number_field :age, {:class => "form-control", :placeholder => "Ingrese edad", required:'true'} %>
    </div>
  </div>


  <div class="item form-group<%= @employee.errors[:blood_type].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :blood_type, "Tipo de Sangre: " %>
    <div class="input-group">
      <%= f.text_field :blood_type, {:class => "form-control", :placeholder => "Ingrese tipo sangre", required:'true'} %>
      <%if @employee.errors[:blood_type].any? %>
        <p class="bg-danger"><%= @employee.errors[:blood_type].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:phone].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :phone, "Teléfono de Contacto: " %>
    <div class="input-group">
      <%= f.number_field :phone, {:class => "form-control", :placeholder => "Ingrese teléfono de contacto", required:'true'} %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:emergency_number].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :emergency_number, "Teléfono en Caso de Emergencia: " %>
    <div class="input-group">
      <%= f.number_field :emergency_number, {:class => "form-control", :placeholder => "Ingrese teléfono de emergencia", required:'true'} %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:weight].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :weight, "Peso: " %>
    <div class="input-group">
      <%= f.number_field :weight, {:class => "form-control", :placeholder => "Ingrese peso", required:'true'} %>
      <div class="input-group-append">
        <span class="input-group-text">kg</span>
      </div>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:size].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :size, "Altura: " %>
    <div class="input-group">
      <%= f.text_field :size, {:class => "form-control", :placeholder => "Ingrese Altura"} %>
    </div>
  </div>

  <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
    <%= f.submit @employee.new_record? ? "Crear empleado" : "Actualizar empleado", :class => "btn btn-success"  %>
  </div>
<% end %>

app/views/employees/_modal_employees.html.erb
<!-- Modal -->
<div class="modal fade" id="modalEmployees" tabindex="-1" role="dialog" aria-labelledby="modalEmployees" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-employees-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-employees modal-body" id="modal-body-employees">

      </div>
      <div class="modal-footer" id="modal-footer-employees">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/employees/create.js.erb
$('#modalEmployees').modal('toggle');
$('#tablaEmployees').append(
    '<tr id="employee_<%= @employee.id %>"><td><%= @employee.document_number %></td><td><%= @employee.name %></td><td><%= @employee.organizational_unit %></td><td><%= @employee.position %></td><td><%= @employee.gender.description %></td><td><%= @employee.eps %></td><td><%= @employee.age %></td><td><%= @employee.blood_type %></td><td><%= @employee.phone %></td><td><%= @employee.emergency_number %></td><td><%= @employee.weight %></td><td><%= @employee.size %></td><td><%= @employee.imc %></td><td><%= @employee.interpretation %></td><td><%= link_to 'editar', edit_employee_path(@employee), html_options = {class: "btn btn-info btn-xs", remote: true} %><%= link_to "Borrar", @employee, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el empleado: #{@employee.name}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
)

$('#agent_name_validation').on('input', function () {
    if (!/[a-z]$/.test(this.value)) {
        this.value = this.value.slice(0, -1);
    }
});

app/views/employees/destroy.js.erb
$('#employee_<%= @employee.id %>').fadeOut();

app/views/employees/edit.js.erb
//add the dialog title
$('#modal-employees-title').html("Editar Empleado");

//Render the new form
$('.modal-body-employees').html('<%= j render("form") %>');

//Show the dynamic dialog
$('#modalEmployees').modal("show");

app/views/employees/index.html.erb
<div style="align-items: center;
    align-content: center;
    flex-direction: column;
    justify-content: center;
    display: flex; margin-top: 5%"><h5
  class="h3 mb-2 text-gray-800 ">Registro de Empleados
  <h1 class="fas fa-user-friends"></h1>
</h5>
</div>

<p style="font-size: 20px">Búsqueda de empleados</p>
<%= form_tag(search_employees_path, :method => "get", class: 'navbar-form navbar-left') do %>
  <div class="input-group", id="searchEmployee">
    <%= search_field_tag :search, params[:search], placeholder: "Ingrese número de documento", class: "form-control col-md-4"%>
    <div class="input-group-btn">
      <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
    </div>
  </div>
<% end %>

<div style="margin-top: 5%">
  <%= link_to new_employee_path, {remote: true, class: "btn btn-info", id: "anadir-employee-btn"} do %>
    <span>Registro</span>
    <% end %>
</div>

<div class="card shadow mb-4" >
  <div class="card-body">
    <div class="table-responsive">
      <% if !@error %>
      <table id="tablaEmployees" class="table table-bordered table-responsive boder-table-t " width="90%">
        <thead>

          <tr>
            <th>Documento de Identidad</th>
            <th>Nombre</th>
            <th>Unidad Organizativa</th>
            <th>Cargo</th>
            <th>Género</th>
            <th>EPS</th>
            <th>Edad</th>
            <th>Grupo Sanguíneo</th>
            <th>Teléfono de Contacto</th>
            <th>Teléfono en Caso de Emergencia</th>
            <th>Peso</th>
            <th>Altura</th>
            <th>IMC</th>
            <th>Interpretación</th>
          </tr>
        </thead>
          <tbody>
            <% @employees.each do |emp| %>
              <tr id="employee_<%= emp.id %>">
                <td><%= emp.document_number %></td>
                <td><%= emp.name %></td>
                <td><%= emp.organizational_unit %></td>
                <td><%= emp.position %></td>
                <td><%= emp.gender.description %></td>
                <td><%= emp.eps %></td>
                <td><%= emp.age %></td>
                <td><%= emp.blood_type %></td>
                <td><%= emp.phone %></td>
                <td><%= emp.emergency_number %></td>
                <td><%= emp.weight %></td>
                <td><%= emp.size %></td>
                <td><%= emp.imc %></td>
                <td><%= emp.interpretation %></td>
                  <td>
                    <%= link_to "Editar", edit_employee_path(emp), html_options = {class: "btn btn-info btn-xs", remote: true}%>
                    <%= link_to "Borrar", emp, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el empleado: #{emp.name}?"}, class: "btn btn-danger btn-xs" %>
                  </td>
              </tr>
            <% end %>
          </tbody>
      </table>
        <% else %>
      <h1> El usuario no existe</h1>
      <% end %>
    </div>
  </div>

<!--      <ul class="pagination justify-content-center" style="margin-top: -2%">-->
<!--        <li class="disablesd"> <%#= will_paginate @employees,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"small-font",:outer_window => 1,:inner_window => 0, list_classes: %w(pagination justify-content-center) %></li>-->
<!--      </ul>-->
<!--  <div>-->
<!--    <span style="align-items: center;-->
<!--        align-content: center;-->
<!--        justify-content: center;-->
<!--        display: flex;" >-->
<!--      <%#= page_entries_info(@employees) %></span>-->
<!--  </div>-->

</div>
<%=render 'modal_employees' %>
<%= render 'sweetify/alert' %>

app/views/employees/new.js.erb
// add the dialog title
$('#modal-employees-title').html("Nuevo empleado");

//render the new form
$('.modal-body-employees').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modalEmployees').modal("show");

app/views/employees/update.js.erb
$('#modalEmployees').modal('toggle');
$('#employee_<%= @employee.id %>').replaceWith(
    '<tr id="employee_<%= @employee.id %>"><td><%= @employee.document_number %></td><td><%= @employee.name %></td><td><%= @employee.organizational_unit %></td><td><%= @employee.position %></td><td><%= @employee.gender.description %></td><td><%= @employee.eps %></td><td><%= @employee.age %></td><td><%= @employee.blood_type %></td><td><%= @employee.phone %></td><td><%= @employee.emergency_number %></td><td><%= @employee.weight %></td><td><%= @employee.size %></td><td><%= @employee.imc %></td><td><%= @employee.interpretation %></td><td><%= link_to 'editar', edit_employee_path(@employee), html_options = {class: "btn btn-info btn-xs", remote: true} %><%= link_to "Borrar", @employee, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el empleado: #{@employee.name}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
)