config/routes.rb
Rails.application.routes.draw do

  resources :exit_surveys, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'exit_surveys#index', :as => 'search'
      post 'reports/output_reports.xls', to: 'exit_surveys#output_reports'
    end
   end
  devise_for :users
  root to: 'home#index'
  resources :employees, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'employees#index', :as => 'search'
    end
end

  resources :entrance_surveys, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'entrance_surveys#index', :as => 'search'
      post 'reports/entrance_surveys.xls', to: 'entrance_surveys#xls_report'
    end
  end

  resources :reports

end

app/models/exit_survey.rb
class ExitSurvey < ApplicationRecord
  belongs_to :employee
end

app/controllers/exit_surveys_controller.rb
class ExitSurveysController < ApplicationController
  before_action :set_exit_survey, only: [:show, :edit, :update, :destroy]

  $user = ""

  def index
    exit_surveys = params[:search].to_i
    @exit_surveys = ExitSurvey.all
    #.paginate(:page => params[:page], :per_page => 5)
    result = Employee.find_by_document_number(exit_surveys)
    if result && exit_surveys == result.document_number

      $user = result.id
      @exit_surveys = ExitSurvey.where(employee_id: $user)
    else

    end
  end

  def output_reports
    @exit_survey = ExitSurvey.all
    render xlsx: "Reporte de salida#{Time.now.strftime('%d%m%Y%H%M%S')} ", template: 'reports/output_reports .xlsx.axlsx'
  end


  # GET /exit_surveys/new
  def new
    @exit_survey = ExitSurvey.new
  end

  # GET /exit_surveys/1/edit
  def edit
  end

  # POST /exit_surveys
  # POST /exit_surveys.json
  def create
    @exit_survey = ExitSurvey.new(exit_survey_params)
    @exit_survey.date = Time.now
    @exit_survey.hour = Time.now.strftime("%I:%M %p")
    @exit_survey.employee_id = $user
    if @exit_survey.recorded_temperature_exit.to_i >= 38
      sweetalert_warning("La temperatura del empleado #{@exit_survey.employee.name} con numero de documento #{@exit_survey.employee.document_number} es mayor 38°C, es necesario tomar nuevamente la temperatura transcurridos 15 minutos", 'Temperatura alta', persistent: 'Aceptar')
      redirect_to action: :create
      @exit_survey.save
    else
      @exit_survey.recorded_temperature_exit.to_s
      respond_to do |format|
        if @exit_survey.save
          sweetalert_success("La encuesta de #{@exit_survey.employee.name} se ha creado con exito", 'Creado', persistent: 'Aceptar')
          redirect_to action: :create
          format.json { head :no_content }
          format.js
        else
          format.json { render json: @exit_survey.errors.full_messages, status: :unprocessable_entity }
          format.js { render :new }
        end
      end
    end
  end

  # PATCH/PUT /exit_surveys/1
  # PATCH/PUT /exit_surveys/1.json
  def update
    respond_to do |format|
      if @exit_survey.update(exit_survey_params)
        sweetalert_success("La encuesta de #{@exit_survey.employee.name} se ha editado con exito", 'Actualizado', persistent: 'Aceptar')
        redirect_to action: :index
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @exit_survey.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  # DELETE /exit_surveys/1
  # DELETE /exit_surveys/1.json
  def destroy
    @exit_survey.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exit_survey
    @exit_survey = ExitSurvey.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exit_survey_params
    params.require(:exit_survey).permit(:recorded_temperature_exit, :new_temperature_recorded_exit, :sore_throat_exit, :nasal_congestion_exit, :cough_exit, :difficulty_breathing_exit, :fatigue_exit, :shaking_chills_exit, :muscle_pain_exit, :other_respiratory_symptom_exit, :which_respiratory_symptom_exit, :disposable_face_mask_exit, :respirator_exit, :latex_gloves_exit, :nitrile_gloves_exit, :rubber_gloves_exit, :another_item_exit, :which_other_element_exit, :does_not_apply_protection_exit, :does_not_apply_because_exit, :hand_disinfection_exit, :discard_used_items_exit, :disinfection_element_exit, :employee_id, :date, :hour)
  end
end

app/helpers/exit_surveys_helper.rb
module ExitSurveysHelper
end

app/views/exit_surveys/_form.html.erb
<%= form_for @exit_survey, {remote: true, multiple: true} do |f| %>
  <div class="form-group">
    <h4 class="control-label">Datos de la encuesta:</h4>
  </div>
  <style>
    .classcheck {
      position: relative;
      top: 30px;
    }
    .classcheck2 {
      position: relative;
      top: 60px;
    }
  </style>

  <script>
      function habilitar(value)
      {
          if(value==true)
          {
              document.getElementById("entrada").disabled=false;
          }else if(value==false){
              document.getElementById("entrada").disabled=true;
          }
      }
      function habilitar2(value)
      {
          if(value==true)
          {
              document.getElementById("entrada2").disabled=false;
          }else if(value==false){
              document.getElementById("entrada2").disabled=true;
          }
      }
  </script>

        <div class="form-group">
          <%= f.label :recorded_temperature_exit, 'Temperatura registrada',{:style => "font-size: 21px"}%>
          <%= f.text_field  :recorded_temperature_exit, {:class => "form-control", :placeholder =>"Ingrese temperatura en ºC "} %>
        </div>
        <div class="form-group">
          <%= f.label :new_temperature_recorded_exit, 'Temperatura nueva registrada',{:style => "font-size: 21px"}%>
          <%= f.text_field  :new_temperature_recorded_exit, {:class => "form-control", :placeholder =>"Ingrese nueva temperatura en ºC "} %>
        </div>
        <label style="align-items: center;
            align-content: center;
            flex-direction: column;
            justify-content: center;
            font-size: 21px;
            display: flex; ">Presenta los siguientes síntomas</label>
        <table class="table table-bordered" width="90%">
          <tr>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init"> Dolor de garganta</label>

                <div class="table-label-int">
                  <div>
                    <%= f.check_box :sore_throat_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Congestión nasal</label>

                <div class="table-label-int">
                  <div class="classcheck">
                    <%= f.check_box :nasal_congestion_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Tos</label>

                <div class="table-label-int">
                  <div class="classcheck">
                    <%= f.check_box :cough_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Dificultad para respirar</label>

                <div class="table-label-int">
                  <div>
                    <%= f.check_box :difficulty_breathing_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
          <tr>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Fatiga</label>

                <div class="table-label-int">
                  <div class="classcheck">
                    <%= f.check_box :fatigue_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Escalofríos</label>

                <div class="table-label-int">
                  <div class="classcheck">
                    <%= f.check_box :shaking_chills_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Dolor de músculos</label>

                <div class="table-label-int">
                  <div>
                    <%= f.check_box :muscle_pain_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Otro síntoma respiratorio </label>

                <div class="table-label-int">
                  <div>
                    <%= f.check_box :other_respiratory_symptom_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
        </table>

        <label style="align-items: center;
            align-content: center;
            flex-direction: column;
            justify-content: center;
            font-size: 21px;
            display: flex;"> Describa el síntoma</label>
        <div class="form-group">
          <%= f.text_area :which_respiratory_symptom_exit, {:class => "form-control", :rows => "3" } %>
        </div>

        <label class="controle-exit">Se hace entrega de los siguientes elementos de bioseguridad/protección:</label>
        <table class="table table-bordered" width="90%">
          <tr>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit"> Tapabocas desechable</label>

                <div class="table-label-exit">
                  <div class="classcheck">
                    <%= f.check_box :disposable_face_mask_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Respirador</label>

                <div class="table-label-exit">
                  <div style="position: relative;top: 59px;">
                    <%= f.check_box :respirator_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>

                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Guantes de látex</label>

                <div class="table-label-exit">
                  <div class="classcheck">
                    <%= f.check_box :latex_gloves_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Guantes de nitrilo</label>

                <div class="table-label-exit">
                  <div class="classcheck">
                    <%= f.check_box :nitrile_gloves_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Guantes de caucho</label>

                <div class="table-label-exit">
                  <div>
                    <%= f.check_box :rubber_gloves_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
        </table>


        <div class="form-group">
          <label style="font-size: 21px"> Otro elemento</label>
          <%= f.check_box :another_item_exit, { :class => "form-check-init", :id => "check", :onchange => "habilitar(this.checked);" }, "true", "false" %>
          <%= f.text_field  :which_other_element_exit, {:class => "form-control", :placeholder =>"¿Cuál? ", :id =>"entrada", disabled: true} %>

        </div>
        <label style="font-size: 21px"> No aplica</label>
          <%= f.check_box :does_not_apply_protection_exit, { :class => "form-check-init", :id => "check", :onchange => "habilitar2(this.checked);"  }, "true", "false" %>
        <div class="form-group">
          <%= f.text_field  :does_not_apply_because_exit, {:class => "form-control", :placeholder =>"¿Por qué?", :id =>"entrada2", disabled: true } %>
        </div>

        <label class="controle-exit">Verifique si al finalizar la jornada realizó las siguientes acciones:</label>
        <table class="table table-bordered" width="90%">
          <tr>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit"> Lavado o desinfección de manos</label>

                <div class="table-label-exit">
                  <div class="classcheck2">
                    <%= f.check_box :hand_disinfection_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Desechar los elementos de bioseguridad usados</label>

                <div class="table-label-exit">
                  <div class="classcheck2">
                    <%= f.check_box :discard_used_items_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>

                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Desinfección de los elementos de protección personal permanentes</label>

                <div class="table-label-exit">
                  <div>
                    <%= f.check_box :disinfection_element_exit, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
          </tr>
        </table>


  <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
    <%= f.submit @exit_survey.new_record? ? "Crear salida" : "Actualizar salida", :class => "btn btn-success"%>
  </div>
<% end %>

app/views/exit_surveys/_modal_exit_surveys.html.erb
<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="modalExitSurveys" tabindex="-1" role="dialog" aria-labelledby="modalExitSurveysLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-exit_surveys-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-exit_surveys modal-body" id="modal-body-exit_surveys">

      </div>
      <div class="modal-footer" id="modal-footer-exit_surveys">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/exit_surveys/create.js.erb
$('#modalExitSurveys').modal('toggle');
$('#tablaExitSurveys').append(
    '<tr id="exit_survey_<%= @exit_survey.id %>"><td><%= @exit_survey.employee.document_number %></td><td><%= @exit_survey.employee.name %></td><td><%= @exit_survey.recorded_temperature_exit %></td><td><%= @exit_survey.new_temperature_recorded_exit %></td><td><%= @exit_survey.date %></td><td><%= @exit_survey.hour %></td><td><%= link_to 'editar', edit_exit_survey_path(@exit_survey), html_options = {class: "btn btn-info btn-xs", remote: true} %><%= link_to "Borrar", @exit_survey, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el registro de: #{@exit_survey.employee.name}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
)

app/views/exit_surveys/destroy.js.erb
$('#exit_survey_<%= @exit_survey.id %>').fadeOut();

app/views/exit_surveys/edit.js.erb
$('#modal-exit_surveys-title').html("Editar encuesta");

$('.modal-body-exit_surveys').html('<%= j render("form") %>');

$('#modalExitSurveys').modal("show");

app/views/exit_surveys/index.html.erb
<div style="align-items: center;
    align-content: center;
    flex-direction: column;
    justify-content: center;
    display: flex; margin-top: 5%"><h5
  class="h3 mb-2 text-gray-800 ">Encuesta de salida
  <h1 class="fas fa-poll-h"></h1>
</h5>
</div>


<p style="font-size: 20px">Búsqueda de empleados</p>
<%= form_tag(search_exit_surveys_path, :method => "get", class: 'navbar-form navbar-left') do %>
  <div class="input-group", id="searchEmployee">
    <%= search_field_tag :search, params[:search], placeholder: "Ingrese número de documento", class: "form-control col-md-4"%>
    <div class="input-group-btn">
      <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
    </div>
  </div>
<% end %>

<div style="margin-top: 5%;  margin-left: 10%">
  <%= link_to new_exit_survey_path, {remote: true, class: "btn btn-info", id: "anadir-exit_survey-btn"} do %>
    <span>Nueva encuesta</span>
  <% end %>
</div>
<br>
<div class="card shadow mb-4" style="width: 80%; margin-left: 10%" >
  <div class="card-body">
    <div class="table-responsive">
      <table id="tablaExitSurveys" class="table table-bordered table-responsive boder-table-t" width="90%">
        <thead>
        <tr>
          <th>Documento de Identidad</th>
          <th>Nombre</th>
          <th>Tempera Registrada</th>
          <th>Temperatura Nueva Registrada</th>
          <th>Fecha de entrada</th>
          <th>Hora de entrada</th>
        </tr>
        </thead>
        <tbody>

        <% @exit_surveys.each do |exit| %>
          <tr id="exit_survey_<%= exit.id %>">
            <td><%= exit.employee&.document_number %></td>
            <td><%= exit.employee&.name %></td>
            <td><%= exit.recorded_temperature_exit %></td>
            <td><%= exit.new_temperature_recorded_exit%></td>
            <td><%= exit.date%></td>
            <td><%= exit.hour%></td>
            <td>
              <%= link_to "Editar", edit_exit_survey_path(exit), html_options = {class: "btn btn-info btn-xs", remote: true}%>
              <%= link_to "Borrar", exit, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el registro de: #{exit.employee&.name}?"}, class: "btn btn-danger btn-xs" %>
            </td>
          </tr>
        <% end %>


        </tbody>
      </table>
    </div>
  </div>
<!--  <ul class="pagination justify-content-center" style="margin-top: -2%">-->
<!--    <li class="disablesd"> <%#= will_paginate(@exit_surveys,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"small-font",:outer_window => 1,:inner_window => 0, list_classes: %w(pagination justify-content-center) )%></li>-->
<!--  </ul>-->

<!--  <div>-->
<!--    <span style="align-items: center;-->
<!--        align-content: center;-->
<!--        justify-content: center;-->
<!--        display: flex;">-->
<!--      <%#= page_entries_info(@exit_surveys) %></span>-->
<!--  </div>-->
</div>

<%=render 'modal_exit_surveys' %>
<%= render 'sweetify/alert' %>

app/views/exit_surveys/new.js.erb
$('#modal-exit_surveys-title').html("Nueva encuesta");

$('.modal-body-exit_surveys').html('<%= j render("form") %>');

//show the dynamic dialog
$('#modalExitSurveys').modal("show");

app/views/exit_surveys/update.js.erb
$('#modalExitSurveys').modal('toggle');

$('#exit_survey_<%= @exit_survey.id %>').replaceWith(
    '<tr id="exit_survey_<%= @exit_survey.id %>"><td><%= @exit_survey.employee.document_number %></td><td><%= @exit_survey.employee.name %></td><td><%= @exit_survey.recorded_temperature %></td><td><%= @exit_survey.new_temperature_recorded_exit %></td><td><%= @exit_survey.date %></td><td><%= @exit_survey.hour %></td><td><%= link_to 'editar', edit_exit_survey_path(@exit_survey), html_options = {class: "btn btn-info btn-xs", remote: true} %><%= link_to "Borrar", @exit_survey, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el registro de: #{@exit_survey.employee.name}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
)