config/routes.rb
Rails.application.routes.draw do

  resources :exit_surveys, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'exit_surveys#index', :as => 'search'
      post 'reports/output_reports.xls', to: 'exit_surveys#output_reports'
    end
   end
  devise_for :users
  root to: 'home#index'
  resources :employees, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'employees#index', :as => 'search'
    end
end

  resources :entrance_surveys, only: [:index, :create, :update, :destroy, :edit, :new] do
    collection do
      get '/search' => 'entrance_surveys#index', :as => 'search'
      post 'reports/entrance_surveys.xls', to: 'entrance_surveys#xls_report'
    end
  end

  resources :reports

end

app/models/entrance_survey.rb
class EntranceSurvey < ApplicationRecord
  belongs_to :employee
end

app/controllers/entrance_surveys_controller.rb
class EntranceSurveysController < ApplicationController
  before_action :set_entrance_survey, only: [:edit, :update, :destroy]

  @value = 38

  $user = ""

  def index
    entrance_surveys = params[:search].to_i
    @entrance_surveys = EntranceSurvey.all
    #.paginate(:page => params[:page], :per_page => 5)
    result = Employee.find_by_document_number(entrance_surveys)
    if result && entrance_surveys == result.document_number
      $user = result.id
      @entrance_surveys = EntranceSurvey.where(employee_id: $user)
    end

  end

  def xls_report
    @entrance_survey = EntranceSurvey.all
    render xlsx: "Reporte de entradas#{Time.now.strftime('%d%m%Y%H%M%S')} ", template: 'reports/entrance_surveys.xlsx.axlsx'
  end

  def new
    @entrance_survey = EntranceSurvey.new
  end

  def create
    @entrance_survey = EntranceSurvey.new(entrance_survey_params)
    @entrance_survey.date = Time.now
    @entrance_survey.hour = Time.now.strftime("%I:%M %p")
    @entrance_survey.employee_id = $user
    if @entrance_survey.recorded_temperature.to_i >= 38
      sweetalert_warning("La temperatura del empleado #{@entrance_survey.employee.name} con numero de documento #{@entrance_survey.employee.document_number} es mayor 38°C, es necesario tomar nuevamente la temperatura transcurridos 15 minutos", 'Temperatura alta', persistent: 'Aceptar')
      redirect_to action: :create
      @entrance_survey.save
    else
      @entrance_survey.recorded_temperature.to_s
      respond_to do |format|
        if @entrance_survey.save
          sweetalert_success("La encuesta de #{@entrance_survey.employee.name} se ha creado con exito", 'Creado', persistent: 'Aceptar')
          redirect_to action: :create
          format.json { head :no_content }
          format.js
        else
          format.json { render json: @entrance_survey.errors.full_messages, status: :unprocessable_entity }
          format.js { render :new }
        end
      end
    end
  end

  # def validate_chekbox
  #   else
  #   end
  # end

  def edit
  end

  def update
    respond_to do |format|
      if @entrance_survey.update(entrance_survey_params)
        sweetalert_success("La encuesta de #{@entrance_survey.employee.name} se ha editado con exito", 'Actualizado', persistent: 'Aceptar')
        redirect_to action: :index
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @entrance_survey.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @entrance_survey.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_entrance_survey
    @entrance_survey = EntranceSurvey.find(params[:id])
  end

  def entrance_survey_params
    params.require(:entrance_survey).permit(:recorded_temperature, :new_temperature_recorded, :sore_throat, :nasal_congestion, :cough, :difficulty_breathing, :fatigue, :shaking_chills, :muscle_pain, :other_respiratory_symptom, :which_respiratory_symptom, :disposable_face_mask, :respirator, :latex_gloves, :nitrile_gloves, :rubber_gloves, :another_item, :which_other_element, :does_not_apply_protection, :does_not_apply_because, :hand_disinfection, :discard_used_items, :disinfection_element, :employee_id, :date, :hour)
  end

end

app/views/entrance_surveys/_form.html.erb
<%= form_for @entrance_survey, {remote: true, multiple: true} do |f| %>
  <div class="form-group">
    <h4 class="control-label">Datos de la encuesta:</h4>
  </div>
  <style>
    .classcheck {
      position: relative;
      top: 30px;
    }
    .classcheck2 {
      position: relative;
      top: 60px;
    }
  </style>
      <script>
        function habilitar(value)
        {
            if(value==true)
            {
                document.getElementById("entrada").disabled=false;
            }else if(value==false){
                  document.getElementById("entrada").disabled=true;
            }
        }
        function habilitar2(value)
        {
            if(value==true)
            {
                document.getElementById("entrada2").disabled=false;
            }else if(value==false){
                document.getElementById("entrada2").disabled=true;
            }
        }
    </script>

        <div class="form-group">
          <%= f.label :recorded_temperature, 'Temperatura registrada',{:style => "font-size: 21px"}%>
<<<<<<< HEAD
          
          <%= f.text_field  :recorded_temperature,  {:class => "form-control", :placeholder =>"Ingrese temperatura en ºC "} %>

=======
          <%= f.text_field  :recorded_temperature, {:class => "form-control", :placeholder =>"Ingrese temperatura en ºC ", } %>
>>>>>>> d8dcc264564cd37ca8b1e9d88a4eb075f584e16c
        </div>
        <div class="form-group">
          <%= f.label :new_temperature_recorded, 'Temperatura nueva registrada',{:style => "font-size: 21px"}%>
          <%= f.text_field  :new_temperature_recorded, {:class => "form-control", :placeholder =>"Ingrese nueva temperatura en ºC "} %>
        </div>
        <label style="align-items: center;
            align-content: center;
            flex-direction: column;
            justify-content: center;
            font-size: 21px;
            display: flex; ">Presenta los siguientes síntomas</label>
        <table class="table table-bordered" width="90%">
          <tr>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init"> Dolor de garganta</label>

                <div class="table-label-int">
                  <div>
                    <%= f.check_box :sore_throat, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Congestión nasal</label>

                <div class="table-label-int">
                  <div class="classcheck">
                    <%= f.check_box :nasal_congestion, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Tos</label>

                <div class="table-label-int">
                  <div class="classcheck">
                    <%= f.check_box :cough, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Dificultad para respirar</label>

                <div class="table-label-int">
                  <div>
                    <%= f.check_box :difficulty_breathing, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
          <tr>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Fatiga</label>

                <div class="table-label-int">
                  <div class="classcheck">
                    <%= f.check_box :fatigue, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Escalofríos</label>

                <div class="table-label-int">
                  <div class="classcheck">
                    <%= f.check_box :shaking_chills, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Dolor de músculos</label>

                <div class="table-label-int">
                  <div>
                    <%= f.check_box :muscle_pain, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%;">
              <div class="form-group">
                <label class="controle-init">Otro síntoma respiratorio </label>

                <div class="table-label-int">
                  <div>
                    <%= f.check_box :other_respiratory_symptom, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
        </table>

        <label style="align-items: center;
            align-content: center;
            flex-direction: column;
            justify-content: center;
            font-size: 21px;
            display: flex;"> Describa el síntoma</label>
        <div class="form-group">
          <%= f.text_area :which_respiratory_symptom, {:class => "form-control", :rows => "3" } %>
        </div>

        <label class="controle-exit">Se hace entrega de los siguientes elementos de bioseguridad/protección:</label>
        <table class="table table-bordered" width="90%">
          <tr>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit"> Tapabocas desechable</label>

                <div class="table-label-exit">
                  <div class="classcheck">
                    <%= f.check_box :disposable_face_mask, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Respirador</label>

                <div class="table-label-exit">
                  <div style="position: relative;top: 59px;">
                    <%= f.check_box :respirator, { :class => "form-check-init" }, "true", "false" %>
                  </div>

                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Guantes de látex</label>

                <div class="table-label-exit">
                  <div class="classcheck">
                    <%= f.check_box :latex_gloves, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Guantes de nitrilo</label>

                <div class="table-label-exit">
                  <div class="classcheck">
                    <%= f.check_box :nitrile_gloves, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Guantes de caucho</label>

                <div class="table-label-exit">
                  <div>
                    <%= f.check_box :rubber_gloves, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
        </table>


        <div class="form-group">
          <label style="font-size: 21px"> Otro elemento</label>
          <%= f.check_box :another_item, { :class => "form-check-init", :id => "check", :onchange => "habilitar(this.checked);"}, "true", "false" %>
          <%= f.text_field  :which_other_element, {:class => "form-control", :placeholder =>"¿Cuál?", :id =>"entrada", disabled: true }  %>

        </div>
        <label style="font-size: 21px"> No aplica</label>
          <%= f.check_box :does_not_apply_protection, { :class => "form-check-init", :id => "check", :onchange => "habilitar2(this.checked);" }, "true", "false" %>
        <div class="form-group">
          <%= f.text_field  :does_not_apply_because, {:class => "form-control", :placeholder =>"¿Por qué?", :id =>"entrada2", disabled: true } %>
        </div>

        <label class="controle-exit">Verifique si al iniciar la jornada realizó las siguientes acciones:</label>
        <table class="table table-bordered" width="90%">
          <tr>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit"> Lavado o desinfección de manos</label>

                <div class="table-label-exit">
                  <div class="classcheck2">
                    <%= f.check_box :hand_disinfection, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Desechar los elementos de bioseguridad usados</label>

                <div class="table-label-exit">
                  <div class="classcheck2">
                    <%= f.check_box :discard_used_items, { :class => "form-check-init" }, "true", "false" %>
                  </div>

                </div>
              </div>
            </th>
            <th style="width: 21%; height: 15%">
              <div class="form-group">
                <label class="controle-exit">Desinfección de los elementos de protección personal permanentes</label>

                <div class="table-label-exit">
                  <div>
                    <%= f.check_box :disinfection_element, { :class => "form-check-init" }, "true", "false" %>
                  </div>
                </div>
              </div>
            </th>
          </tr>
          </tr>
        </table>


  <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
    <%= f.submit @entrance_survey.new_record? ? "Crear encuesta" : "Actualizar encuesta", :class => "btn btn-success"%>
  </div>
<% end %>

app/views/entrance_surveys/_modal_entrance_surveys.html.erb
<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="modalEntranceSurveys" tabindex="-1" role="dialog" aria-labelledby="modalEntranceSurveysLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-entrance_surveys-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-entrance_surveys modal-body" id="modal-body-entrance_surveys">

      </div>
      <div class="modal-footer" id="modal-footer-entrance_surveys">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/entrance_surveys/create.js.erb
$('#modalEntranceSurveys').modal('toggle');
$('#tablaEntranceSurveys').append(
    '<tr id="entrance_survey_<%= @entrance_survey.id %>"><td><%= @entrance_survey.employee.document_number %></td><td><%= @entrance_survey.employee.name %></td><td><%= @entrance_survey.recorded_temperature %></td><td><%= @entrance_survey.new_temperature_recorded %></td><td><%= @entrance_survey.date %></td><td><%= @entrance_survey.hour %></td><td><%= link_to 'editar', edit_entrance_survey_path(@entrance_survey), html_options = {class: "btn btn-info btn-xs", remote: true} %><%= link_to "Borrar", @entrance_survey, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el registro de: #{@entrance_survey.employee.name}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
)

app/views/entrance_surveys/destroy.js.erb
$('#entrance_survey_<%= @entrance_survey.id %>').fadeOut();

app/views/entrance_surveys/edit.js.erb
$('#modal-entrance_surveys-title').html("Editar encuesta");

$('.modal-body-entrance_surveys').html('<%= j render("form") %>');

$('#modalEntranceSurveys').modal("show");

app/views/entrance_surveys/index.html.erb
 <div style="align-items: center;
    align-content: center;
    flex-direction: column;
    justify-content: center;
    display: flex; margin-top: 5%"><h5
  class="h3 mb-2 text-gray-800 ">Encuesta de entrada
  <h1 class="fas fa-poll"></h1>
</h5>
</div>

<p style="font-size: 20px">Búsqueda de empleados</p>
<%= form_tag(search_entrance_surveys_path, :method => "get", class: 'navbar-form navbar-left') do %>
  <div class="input-group", id="searchEmployee">
    <%= search_field_tag :search, params[:search], placeholder: "Ingrese número de documento", class: "form-control col-md-4"%>
    <div class="input-group-btn">
      <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
    </div>
  </div>
<% end %>

<div style="margin-top: 5%;  margin-left: 10%">
  <%= link_to new_entrance_survey_path, {remote: true, class: "btn btn-info", id: "anadir-entrance_survey-btn"} do %>
    <span>Nueva encuesta</span>
  <% end %>
</div>

  <br>
<div class="card shadow mb-4" style="width: 80%; margin-left: 10%" >
  <div class="card-body">
    <div class="table-responsive">
      <table id="tablaEntranceSurveys" class="table table-bordered table-responsive boder-table-t" width="90%">
        <thead>
        <tr>
          <th>Documento de Identidad</th>
          <th>Nombre</th>
          <th>Tempera Registrada</th>
          <th>Temperatura Nueva Registrada</th>
          <th>Fecha de entrada</th>
          <th>Hora de entrada</th>
        </tr>
        </thead>
        <tbody>


          <% @entrance_surveys.each do |entrance| %>
            <tr id="entrance_survey_<%= entrance.id %>">
              <td><%= entrance.employee&.document_number %></td>
              <td><%= entrance.employee&.name %></td>
              <td><%= entrance.recorded_temperature %></td>
              <td><%= entrance.new_temperature_recorded %></td>
              <td><%= entrance.date%></td>
              <td><%= entrance.hour%></td>
              <td>
                <%= link_to "Editar", edit_entrance_survey_path(entrance), html_options = {class: "btn btn-info btn-xs", remote: true}%>
                <%= link_to "Borrar", entrance, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el registro de: #{entrance.employee&.name}?"}, class: "btn btn-danger btn-xs" %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>

<!--  <ul class="pagination justify-content-center" style="margin-top: -2%">-->
<!--    <li class="disablesd"> <%#= will_paginate(@entrance_surveys,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"small-font",:outer_window => 1,:inner_window => 0, list_classes: %w(pagination justify-content-center) )%></li>-->
<!--  </ul>-->

<!--  <div>-->
<!--    <span style="align-items: center;-->
<!--        align-content: center;-->
<!--        justify-content: center;-->
<!--        display: flex;">-->
<!--      <%#= page_entries_info(@entrance_surveys) %></span>-->
<!--  </div>-->

</div>

<%=render 'modal_entrance_surveys' %>
<%= render 'sweetify/alert' %>

app/views/entrance_surveys/new.js.erb
$('#modal-entrance_surveys-title').html("Nueva encuesta");

$('.modal-body-entrance_surveys').html('<%= j render("form") %>');

//show the dynamic dialog
$('#modalEntranceSurveys').modal("show");

app/views/entrance_surveys/update.js.erb
$('#modalEntranceSurveys').modal('toggle');

$('#entrance_survey_<%= @entrance_survey.id %>').replaceWith(
    '<tr id="entrance_survey_<%= @entrance_survey.id %>"><td><%= @entrance_survey.employee.document_number %></td><td><%= @entrance_survey.employee.name %></td><td><%= @entrance_survey.recorded_temperature %></td><td><%= @entrance_survey.new_temperature_recorded %></td><td><%= @entrance_survey.date %></td><td><%= @entrance_survey.hour %></td><td><%= link_to 'editar', edit_entrance_survey_path(@entrance_survey), html_options = {class: "btn btn-info btn-xs", remote: true} %><%= link_to "Borrar", @entrance_survey, remote: true, method: :delete, data: { confirm: "¿Está seguro que quiere borrar el registro de: #{@entrance_survey.employee.name}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
)